# Template to take colab parameters scoped inside methods (e.g. Root, DeforumArgs, etc.) 
# and generate a parameters.py file with python type hinting
# that can be used by libraries and APIs for validation of input
# the intention is that this file be autogenerated from a source ipynb file.
# This file was automatically generated. Do not edit -- rather rerun the file "extract_colab_parameters.py"
# jinja2 template: parameters.tmpl.py
# example input file: parameters.json

{% for method in methods -%} 
class {{ method }}:
{%- for obj in objects -%}
  {%- if obj.method == method %}
    {%- if obj.type in ["bool","float","int"] %}
      {{ obj.name }}: {{ obj.type }} = {{ obj.default }}
    {%- elif obj.type is none %}
      {{ obj.name }} = "{{ obj.default }}"{% if obj.constraints %}  # {{ obj.constraints }}{% endif %}
    {%- else %}
      {{ obj.name }}: {{ obj.type }} = "{{ obj.default }}"{% if obj.constraints %}  # {{ obj.constraints }}{% endif %}
    {%- endif %}
  {%- endif %}
{%- endfor %}
{% endfor %}